name: CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: compilar o programa principal
        run: gcc jurossimples.c -o jurossimples

      - name: executar o programa principal
        run: ./jurossimples 100 0.5 10

      - name: mostrar o conteudo do arquivo criado
        run: cat jurossimples.txt

      - name: compilar o arquivo de teste
        run: gcc test_jurossimples.c -o test_jurossimples

      - name: executar o arquivo de teste
        run: ./test_jurossimples
